// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mixer/adapter/octarine/config/config.proto

/*
	Package config is a generated protocol buffer package.

	It is generated from these files:
		mixer/adapter/octarine/config/config.proto

	It has these top-level messages:
		Params
*/
package config

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Params struct {
	FlagsFile           string `protobuf:"bytes,1,opt,name=flagsFile,proto3" json:"flagsFile,omitempty"`
	Namespace           string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Deployment          string `protobuf:"bytes,3,opt,name=deployment,proto3" json:"deployment,omitempty"`
	MessageProxyAddress string `protobuf:"bytes,4,opt,name=messageProxyAddress,proto3" json:"messageProxyAddress,omitempty"`
	MessageProxyCA      string `protobuf:"bytes,5,opt,name=messageProxyCA,proto3" json:"messageProxyCA,omitempty"`
	BackendAddress      string `protobuf:"bytes,6,opt,name=backendAddress,proto3" json:"backendAddress,omitempty"`
	InitialAccessToken  string `protobuf:"bytes,7,opt,name=initialAccessToken,proto3" json:"initialAccessToken,omitempty"`
}

func (m *Params) Reset()                    { *m = Params{} }
func (*Params) ProtoMessage()               {}
func (*Params) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{0} }

func (m *Params) GetFlagsFile() string {
	if m != nil {
		return m.FlagsFile
	}
	return ""
}

func (m *Params) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Params) GetDeployment() string {
	if m != nil {
		return m.Deployment
	}
	return ""
}

func (m *Params) GetMessageProxyAddress() string {
	if m != nil {
		return m.MessageProxyAddress
	}
	return ""
}

func (m *Params) GetMessageProxyCA() string {
	if m != nil {
		return m.MessageProxyCA
	}
	return ""
}

func (m *Params) GetBackendAddress() string {
	if m != nil {
		return m.BackendAddress
	}
	return ""
}

func (m *Params) GetInitialAccessToken() string {
	if m != nil {
		return m.InitialAccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "adapter.octarine.config.Params")
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.FlagsFile != that1.FlagsFile {
		return false
	}
	if this.Namespace != that1.Namespace {
		return false
	}
	if this.Deployment != that1.Deployment {
		return false
	}
	if this.MessageProxyAddress != that1.MessageProxyAddress {
		return false
	}
	if this.MessageProxyCA != that1.MessageProxyCA {
		return false
	}
	if this.BackendAddress != that1.BackendAddress {
		return false
	}
	if this.InitialAccessToken != that1.InitialAccessToken {
		return false
	}
	return true
}
func (this *Params) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&config.Params{")
	s = append(s, "FlagsFile: "+fmt.Sprintf("%#v", this.FlagsFile)+",\n")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	s = append(s, "Deployment: "+fmt.Sprintf("%#v", this.Deployment)+",\n")
	s = append(s, "MessageProxyAddress: "+fmt.Sprintf("%#v", this.MessageProxyAddress)+",\n")
	s = append(s, "MessageProxyCA: "+fmt.Sprintf("%#v", this.MessageProxyCA)+",\n")
	s = append(s, "BackendAddress: "+fmt.Sprintf("%#v", this.BackendAddress)+",\n")
	s = append(s, "InitialAccessToken: "+fmt.Sprintf("%#v", this.InitialAccessToken)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringConfig(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.FlagsFile) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintConfig(dAtA, i, uint64(len(m.FlagsFile)))
		i += copy(dAtA[i:], m.FlagsFile)
	}
	if len(m.Namespace) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Namespace)))
		i += copy(dAtA[i:], m.Namespace)
	}
	if len(m.Deployment) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Deployment)))
		i += copy(dAtA[i:], m.Deployment)
	}
	if len(m.MessageProxyAddress) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintConfig(dAtA, i, uint64(len(m.MessageProxyAddress)))
		i += copy(dAtA[i:], m.MessageProxyAddress)
	}
	if len(m.MessageProxyCA) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintConfig(dAtA, i, uint64(len(m.MessageProxyCA)))
		i += copy(dAtA[i:], m.MessageProxyCA)
	}
	if len(m.BackendAddress) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintConfig(dAtA, i, uint64(len(m.BackendAddress)))
		i += copy(dAtA[i:], m.BackendAddress)
	}
	if len(m.InitialAccessToken) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintConfig(dAtA, i, uint64(len(m.InitialAccessToken)))
		i += copy(dAtA[i:], m.InitialAccessToken)
	}
	return i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Params) Size() (n int) {
	var l int
	_ = l
	l = len(m.FlagsFile)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.Deployment)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.MessageProxyAddress)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.MessageProxyCA)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.BackendAddress)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.InitialAccessToken)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Params) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Params{`,
		`FlagsFile:` + fmt.Sprintf("%v", this.FlagsFile) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`Deployment:` + fmt.Sprintf("%v", this.Deployment) + `,`,
		`MessageProxyAddress:` + fmt.Sprintf("%v", this.MessageProxyAddress) + `,`,
		`MessageProxyCA:` + fmt.Sprintf("%v", this.MessageProxyCA) + `,`,
		`BackendAddress:` + fmt.Sprintf("%v", this.BackendAddress) + `,`,
		`InitialAccessToken:` + fmt.Sprintf("%v", this.InitialAccessToken) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringConfig(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FlagsFile", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FlagsFile = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deployment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deployment = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageProxyAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageProxyAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageProxyCA", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageProxyCA = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BackendAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BackendAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialAccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialAccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowConfig
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipConfig(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthConfig = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("mixer/adapter/octarine/config/config.proto", fileDescriptorConfig) }

var fileDescriptorConfig = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4e, 0xf3, 0x30,
	0x14, 0x80, 0xe3, 0xfe, 0x3f, 0x41, 0xf5, 0xc0, 0x60, 0x90, 0x88, 0x2a, 0xf4, 0x84, 0x18, 0x10,
	0x62, 0x48, 0x90, 0xe0, 0x02, 0x05, 0x89, 0xb9, 0x42, 0x4c, 0x6c, 0x6e, 0xf2, 0x6a, 0x59, 0x4d,
	0xec, 0xc8, 0x4e, 0xa5, 0x76, 0xe3, 0x08, 0x4c, 0x9c, 0x81, 0xa3, 0x30, 0x76, 0x64, 0xa4, 0x66,
	0x61, 0xec, 0x11, 0x50, 0xec, 0x16, 0x0a, 0xea, 0xe4, 0xa7, 0xef, 0xfb, 0xec, 0xc1, 0x8f, 0x9e,
	0x57, 0x72, 0x8a, 0x26, 0xe3, 0x05, 0xaf, 0x1b, 0x34, 0x99, 0xce, 0x1b, 0x6e, 0xa4, 0xc2, 0x2c,
	0xd7, 0x6a, 0x24, 0xc5, 0xea, 0x48, 0x6b, 0xa3, 0x1b, 0xcd, 0x0e, 0x57, 0x55, 0xba, 0xae, 0xd2,
	0xa0, 0x7b, 0x20, 0xb4, 0x16, 0x25, 0x66, 0x3e, 0x1b, 0x4e, 0x46, 0x59, 0x31, 0x31, 0xbc, 0x91,
	0x5a, 0x85, 0x8b, 0xbd, 0x03, 0xa1, 0x85, 0xf6, 0x63, 0xd6, 0x4e, 0x81, 0x9e, 0x3c, 0x77, 0x68,
	0x3c, 0xe0, 0x86, 0x57, 0x96, 0x1d, 0xd1, 0xee, 0xa8, 0xe4, 0xc2, 0xde, 0xca, 0x12, 0x13, 0x72,
	0x4c, 0xce, 0xba, 0x77, 0x3f, 0xa0, 0xb5, 0x8a, 0x57, 0x68, 0x6b, 0x9e, 0x63, 0xd2, 0x09, 0xf6,
	0x1b, 0x30, 0xa0, 0xb4, 0xc0, 0xba, 0xd4, 0xb3, 0x0a, 0x55, 0x93, 0xfc, 0xf3, 0x7a, 0x83, 0xb0,
	0x0b, 0xba, 0x5f, 0xa1, 0xb5, 0x5c, 0xe0, 0xc0, 0xe8, 0xe9, 0xac, 0x5f, 0x14, 0x06, 0xad, 0x4d,
	0xfe, 0xfb, 0x70, 0x9b, 0x62, 0xa7, 0x74, 0x6f, 0x13, 0xdf, 0xf4, 0x93, 0x1d, 0x1f, 0xff, 0xa1,
	0x6d, 0x37, 0xe4, 0xf9, 0x18, 0x55, 0xb1, 0x7e, 0x34, 0x0e, 0xdd, 0x6f, 0xca, 0x52, 0xca, 0xa4,
	0x92, 0x8d, 0xe4, 0x65, 0x3f, 0xcf, 0xd1, 0xda, 0x7b, 0x3d, 0x46, 0x95, 0xec, 0xfa, 0x76, 0x8b,
	0xb9, 0xbe, 0x9a, 0x2f, 0x20, 0x7a, 0x5b, 0x40, 0xb4, 0x5c, 0x00, 0x79, 0x74, 0x40, 0x5e, 0x1c,
	0x90, 0x57, 0x07, 0x64, 0xee, 0x80, 0xbc, 0x3b, 0x20, 0x9f, 0x0e, 0xa2, 0xa5, 0x03, 0xf2, 0xf4,
	0x01, 0xd1, 0x43, 0x1c, 0x96, 0x30, 0x8c, 0xfd, 0xaf, 0x5e, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x21, 0xbb, 0x4e, 0x07, 0xd2, 0x01, 0x00, 0x00,
}
